# 2025-26 Project

### Notes

1. It is mandatory to use GitHub for developing the project.
2. The project must be a jupyter notebook.
3. There is no restriction on the libraries that can be used, nor on the Python version.
4. All questions on the project **must** be asked in the Discussion forum on the course website.
5. At most 3 students can be in each group. You must create the groups by yourself. You can use the Discussion forum to create the groups.
6. You do not have to send me the project *before* the discussion.
7. You do not have to prepare any slides for the discussion.
8. You can use AI tools, but you have to describe in the notebook how you have used such tools and you have to show that you have fully understood **everything** that you have in your project.


### 1. Create a single dataframe with the concatenation of all input csv files, adding a column called `country`

In [4]:
import pandas as pd
import zstandard
import io

In [5]:
countries = ["CA", "DE", "FR", "GB", "IN", "JP", "KR", "MX", "RU", "US"]
dfs = {}

for element in countries:
    path = fr"FCS/{element}videos.csv.zst"
    
    try:
        with open(path, "rb") as f: #binary reading to decompress
            dctx = zstandard.ZstdDecompressor() #object to decompress
            decompressed = dctx.decompress(f.read()) #read the decompressed file
            text = decompressed.decode("utf-8", errors="replace") #transform the decompress file in a readable format for humans (CSV) and cover errors
            dfs[element] = pd.read_csv(io.StringIO(text)) #we expect a csv file not a string to read it, so we convert the string in a csv
            
            dfs[element]['trending_date'] = pd.to_datetime(dfs[element]['trending_date'],format='%y.%d.%m')
            dfs[element]['publish_time'] = pd.to_datetime(dfs[element]['publish_time'])
            dfs[element]["country"] = element
            
    except Exception as e:
        print(f"✗ Errore durante la decompressione di {element}: {e}")

final_dataframe = pd.concat(dfs.values(), ignore_index=True)
final_dataframe

Totale righe: 375942

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,BZt0qjTWNhw,2018-06-14,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18 13:00:04+00:00,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US
375938,1h7KV2sjUWY,2018-06-14,True Facts : Ant Mutualism,zefrank1,22,2018-05-18 01:00:06+00:00,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
375939,D6Oy4LfoqsU,2018-06-14,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22+00:00,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US
375940,oV0zkMe1K8s,2018-06-14,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US
375941,ooyjaVdt-jA,2018-06-14,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US

### 2. Extract all videos that have no tag.

In [6]:
empty = final_dataframe[final_dataframe['tags'] == '[none]']
empty
# no tag = [none]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
41,JwboxqDylgg,2017-11-14,Canada Soccer's Women's National Team v USA In...,Canada Soccer,17,2017-11-13 05:53:49+00:00,[none],36311,277,28,13,https://i.ytimg.com/vi/JwboxqDylgg/default.jpg,False,False,False,Canada Soccer's Women's National Team face riv...,CA
58,9B-q8h31Bpk,2017-11-14,John Oliver Tackles Louis C.K. And Donald Trum...,TV Shows,22,2017-11-13 04:49:26+00:00,[none],106029,1270,101,181,https://i.ytimg.com/vi/9B-q8h31Bpk/default.jpg,False,False,False,"John Oliver on News, Politics ...",CA
78,1UE5Dq1rvUA,2017-11-14,Taylor Swift Perform Ready For It - SNL,Ken Reactz,24,2017-11-12 05:18:02+00:00,[none],320964,8069,285,717,https://i.ytimg.com/vi/1UE5Dq1rvUA/default.jpg,False,False,False,Thanks for watching please subscribe and subsc...,CA
86,pmJQ4KwliX4,2017-11-14,"LATEST Q POSTS: ROTHSCHILDS, HOUSE OF SAUD, lL...",James Munder,2,2017-11-12 21:25:40+00:00,[none],116820,1503,139,1066,https://i.ytimg.com/vi/pmJQ4KwliX4/default.jpg,False,False,False,https://pastebin.ca/3930472\n\nSupport My Chan...,CA
98,lHcXhBojpeQ,2017-11-14,三屆TVB視帝，拋棄10年青梅竹馬髮妻，為娶小三還不惜與母絕交！,明星百曉生,22,2017-11-12 12:49:50+00:00,[none],88061,47,58,17,https://i.ytimg.com/vi/lHcXhBojpeQ/default.jpg,False,False,False,NaN,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375815,VGykknw9eCM,2018-06-14,"Made Defiant: The Mixtape ft. Neymar Jr., Kane...",Beats by Dre,10,2018-06-07 07:01:06+00:00,[none],3577614,12318,1345,1414,https://i.ytimg.com/vi/VGykknw9eCM/default.jpg,False,False,False,"When your time comes, you have two choices. Yo...",US
375819,fAIX12F6958,2018-06-14,Bumblebee (2018) - Official Teaser Trailer - P...,Paramount Pictures,1,2018-06-05 07:00:01+00:00,[none],19864779,228670,16420,46318,https://i.ytimg.com/vi/fAIX12F6958/default.jpg,False,False,False,Every adventure has a beginning. Watch the off...,US
375865,gS1DbvHHVH0,2018-06-14,Going in to brain surgery,Simone Giertz,28,2018-05-30 14:22:13+00:00,[none],1635301,120791,1098,20711,https://i.ytimg.com/vi/gS1DbvHHVH0/default.jpg,False,False,False,We’ll post an update on Instagram and Twitter ...,US
375873,E4c7EE8_IX0,2018-06-14,Weezer - Africa,weezer,10,2018-05-29 12:00:11+00:00,[none],4682557,115240,5069,9170,https://i.ytimg.com/vi/E4c7EE8_IX0/default.jpg,False,False,False,Stream + download the song: http://fanlink.to/...,US
375938,1h7KV2sjUWY,2018-06-14,True Facts : Ant Mutualism,zefrank1,22,2018-05-18 01:00:06+00:00,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US

### 3. For each channel, determine the total number of views

In [7]:
# last trending date for each video to remove duplicate titles and have multiple views
ultima_data_trending = final_dataframe.groupby('title')['trending_date'].max()

# filter the database by title and trending date
df_ultima_data = final_dataframe[
    final_dataframe.set_index(['title', 'trending_date'])
    .index.isin(list(ultima_data_trending.items()))
]

# total number of views for each channel
risultatos = df_ultima_data.groupby('channel_title')['views'].sum().sort_values()
risultatos

channel_title
Alexander Redking                           153
Sport Life                                  163
No Comment TV                               284
Videostendencias                            302
NavylittleMonster                           365
                                        ...
MLG Highlights                        503735778
The Late Show with Stephen Colbert    524766124
PewDiePie                             577916815
NickyJamTV                            641732857
T-Series                              864221128
Name: views, Length: 37690, dtype: int64

### 4. Save all rows with disabled comments and disabled ratings, or that have `video_error_or_removed` in a new dataframe called `excluded`, and remove those rows from the original dataframe.

In [8]:
ex1 = final_dataframe[(final_dataframe['comments_disabled'] == True) & (final_dataframe['ratings_disabled'] == True)] #2367
ex2 = final_dataframe[final_dataframe['video_error_or_removed'] == True]#253
#2620

excluded = pd.concat([ex1, ex2])  #2438

final_dataframe = final_dataframe[~final_dataframe.isin(excluded).any(axis=1)] #duplicates are considered and deleted
#len(final_dataframe)
final_dataframe
#duplicati = excluded[excluded.duplicated()] duplicates #182
#intersezione = pd.merge(excluded, duplicati)
#intersezione.head(10)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,BZt0qjTWNhw,2018-06-14,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18 13:00:04+00:00,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US
375938,1h7KV2sjUWY,2018-06-14,True Facts : Ant Mutualism,zefrank1,22,2018-05-18 01:00:06+00:00,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
375939,D6Oy4LfoqsU,2018-06-14,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22+00:00,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US
375940,oV0zkMe1K8s,2018-06-14,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US
375941,ooyjaVdt-jA,2018-06-14,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US

### 5. Add a `like_ratio` column storing the ratio between the number of likes and of dislikes

In [9]:
import numpy as np
# we use numpy library to avoid problems where ['dislikes'] == 0 because it reaches the ratio of +inf
final_dataframe.insert(10, 'like_ratio', np.where(final_dataframe['dislikes'] == 0, None, final_dataframe['likes'] / final_dataframe['dislikes']))
final_dataframe.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,like_ratio,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,18.135076,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,75.707346,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,27.3525,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,66.485168,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,77.513044,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA

In [10]:
#final_dataframe['like_ratio'].max()

### 6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

In [36]:
#divide the day in 144 slots 10 minutes each
final_dataframe.loc[:, 'cluster'] = (final_dataframe['publish_time'].dt.hour * 60 + final_dataframe['publish_time'].dt.minute) // 10
final_dataframe

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,comments_disabled,ratings_disabled,video_error_or_removed,description,country,cluster,supertag,year,month,day
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,102,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",2017,11,14
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,...,False,False,False,STill got a lot of packages. Probably will las...,CA,102,"[plush, bad unboxing, unboxing, fan mail, idub...",2017,11,14
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,...,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,114,"[racist superman, rudy, mancuso, king, bach, r...",2017,11,14
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,...,False,False,False,I know it's been a while since we did this sho...,CA,108,"[ryan, higa, higatv, nigahiga, i dare you, idy...",2017,11,14
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,...,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,66,"[edsheeran, ed sheeran, acoustic, live, cover,...",2017,11,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,BZt0qjTWNhw,2018-06-14,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18 13:00:04+00:00,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,...,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US,78,"[aarons animals, aarons, animals, cat, cats, k...",2018,6,14
375938,1h7KV2sjUWY,2018-06-14,True Facts : Ant Mutualism,zefrank1,22,2018-05-18 01:00:06+00:00,[none],1064798,60008,382,...,False,False,False,NaN,US,6,[[none]],2018,6,14
375939,D6Oy4LfoqsU,2018-06-14,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22+00:00,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,...,False,False,False,I had so much fun transforming Safiyas hair in...,US,105,[I gave safiya nygaard a perfect hair makeover...,2018,6,14
375940,oV0zkMe1K8s,2018-06-14,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,...,False,False,False,How Black Panther Should Have EndedWatch More ...,US,102,"[Black Panther, HISHE, Marvel, Infinity War, H...",2018,6,14
375941,ooyjaVdt-jA,2018-06-14,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,...,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,102,"[call of duty, cod, activision, Black Ops 4]",2018,6,14


### 7. For each interval, determine the number of videos, average number of likes and of dislikes.

In [12]:
#create a function to save the interval number in a string
def cluster_to_time(cluster):
    minutes = cluster * 10
    hours = minutes // 60
    remaining_minutes = minutes % 60
    start_time = f"{hours:02d}:{remaining_minutes:02d}" #format integer with 2 figures for each hours and minutes
    end_time = f"{(minutes + 10) // 60:02d}:{(minutes + 10) % 60:02d}" #calculate the interval by the minutes numbers
    return f"{start_time} - {end_time}" 

avg = final_dataframe[['likes','dislikes']].groupby(final_dataframe['cluster']).mean().round(0)
suum = final_dataframe['video_id'].groupby(final_dataframe['cluster']).count()
clu = avg.join(suum.rename('count'))
clu.loc[:, 'interval'] = clu.index.map(cluster_to_time)
clu

           likes  dislikes  count       interval
cluster
0        61288.0    3808.0   2897  00:00 - 00:10
1        22748.0    1450.0   1509  00:10 - 00:20
2        21378.0    1072.0   1241  00:20 - 00:30
3        36854.0     956.0   1614  00:30 - 00:40
4        42199.0    1909.0   1269  00:40 - 00:50
...          ...       ...    ...            ...
139      22784.0    1110.0   1554  23:10 - 23:20
140      30697.0    1177.0   1438  23:20 - 23:30
141      18159.0     874.0   1666  23:30 - 23:40
142      45737.0    9342.0   1466  23:40 - 23:50
143      10854.0     506.0   1269  23:50 - 24:00

[144 rows x 4 columns]

### 8. For each tag, determine the number of videos
Notice that `tags` contains a string with several tags.

In [37]:
#final_dataframe.loc[:,'supertag'] = final_dataframe['tags'].str.replace('[none]','') #try to see if there are others none values
final_dataframe.loc[:,'supertag'] = final_dataframe['tags'].str.replace('"','') #clean the string
#create the list
final_dataframe.loc[:,'supertag'] = final_dataframe['supertag'].str.split("|") #split the string
notag_dataframe = final_dataframe[~final_dataframe.isin(empty).any(axis=1)] #filter the new dataset without none or empty tags

# last trending date for each video to remove duplicate titles and have multiple tags
ultima_data_trendings = notag_dataframe.groupby('title')['trending_date'].max()
ultima_data_trendings

# filter the database by title and trending date to avoid the duplicates
df_ultima_datas = notag_dataframe[
    notag_dataframe.set_index(['title', 'trending_date'])
    .index.isin(list(ultima_data_trendings.items()))
]

df_ultima_datas['supertag'].head(20)

5     [#DramaAlert, Drama, Alert, DramaAlert, keemst...
12    [電視劇, 大陸電視劇, 猎场, 职场, 商战, 爱情, 都市, 胡歌, 陈龙, 孙红雷, ...
13    [punjabi songs, punjabi bhangra, punjabi music...
16          [prank, pranks, nelk, nelkfilmz, nelkfilms]
17    [Graham Norton, Graham Norton Show Official, E...
18    [Rooster Teeth, RT, animation, television, fil...
24    [80s music, 80s songs, madonna, DO COLLEGE KID...
26    [Industrial Fan, Industrial Fan Destruction, T...
31    [rhett and link, good mythical more, rhett and...
34    [马克, 迪丽热巴, 麻辣变形计, 军旅, 美女, 感情, 都市, 电视剧, 热播, 火辣,...
36    [Achievement Hunter, AH, video game, gaming, g...
38    [sugar pine 7, steven suptic, autumn, sick, pa...
39    [danny duncan, danny duncan 69, kevin, danny d...
42    [artificial intelligence, digital human, virtu...
45    [DNC Chairwoman Donna Brazile, Hacks, The Insi...
47    [Toronto Maple Leafs, Maple Leafs, Leafs, Bost...
48    [squeezie doublage, squeezie batman, squeezie ...
50    [蒙面唱将猜猜猜第二季, 江苏卫视, 灿星制作, 真人秀, 音乐, 综艺, 陶晶莹, 陈嘉桦...
52    [Duterte News Report, Philippines News Cast, T...
56    [stars passed, stars passed away, stars lost, ...
Name: supertag, dtype: object

In [14]:
from collections import Counter
tag_counter = Counter()

# increase the value of the counter
for tags in df_ultima_datas['supertag']:  # Case sensitive
    tag_counter.update(tags)

#for tags in notag_dataframe['supertag']:
#    tags_lower = [tag.lower() for tag in tags]  # Case insensitive
#    tag_counter.update(tags_lower)

results = pd.DataFrame(tag_counter.items(), columns=['tag', 'count'])
print(results)

# to avoid kernel problems we could filter the results with less than 2 tags and use less computing power
#results_filtered = results[results['count'] != 1]
#print(results_filtered)

                                tag  count
0                       #DramaAlert     56
1                             Drama    368
2                             Alert     58
3                        DramaAlert     56
4                          keemstar     65
...                             ...    ...
847867  haircut for your face shape      1
847868                        HISHE      1
847869     How It Should Have Ended      1
847870                       azerrz      1
847871                     plothole      1

[847872 rows x 2 columns]


### 9. Find the tags with the largest number of videos

In [15]:
results.sort_values(by='count', ascending=False, inplace=True)
results.head(1)

       tag  count
6999  2018   6254


### 10. For each (`tag`, `country`) pair, compute average ratio likes/dislikes

In [16]:
# we use the not filtered dataset 
df1 = final_dataframe.explode('supertag') #divide the list in different columns for each tag
df1 = df1[df1['supertag'].notna() & (df1['supertag'] != '')] #filter not null or na
resulted = (df1.groupby(['supertag', 'country'])['like_ratio'].mean().reset_index()) #compute the value
resulted

                                                supertag country like_ratio
0                                            #Freeticket      IN   2.665679
1                                                  #GST       IN   2.416896
2                                             #Jaisimha       IN   2.665679
3                                        #JanaSenaParty       IN  17.621907
4                                             #MahaaNews      IN   8.511947
...                                                  ...     ...        ...
1098646                                                😥      DE  26.384615
1098647                 😭 #résistancelamaindesqueezie ❤️      FR  10.219048
1098648  😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية      FR   6.223873
1098649                              🚀 smartpixel.com.ua      RU   0.714286
1098650                     🤝 ZARBEX zahlt Schutzgeld!!!      DE  13.989691

[1098651 rows x 3 columns]


### 11. For each (`trending_date`, `country`) pair, the video with the largest number of views

In [17]:
pairs = final_dataframe.groupby(['trending_date', 'country'])['views'].max()
pairs

trending_date  country
2017-11-14     CA         33523622
               DE         33523622
               FR         33523622
               GB         33523622
               IN         35885754
                            ...
2018-06-14     JP          4427381
               KR          4427381
               MX          5829270
               RU          6597033
               US         94254507
Name: views, Length: 1967, dtype: int64


### 12. Divide `trending_date` into three columns: `year`, `month`, `day`

In [38]:
final_dataframe.loc[:, 'year'] = final_dataframe['trending_date'].dt.year
final_dataframe.loc[:, 'month'] = final_dataframe['trending_date'].dt.month
final_dataframe.loc[:, 'day'] = final_dataframe['trending_date'].dt.day
final_dataframe.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,comments_disabled,ratings_disabled,video_error_or_removed,description,country,cluster,supertag,year,month,day
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,102,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",2017,11,14
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,...,False,False,False,STill got a lot of packages. Probably will las...,CA,102,"[plush, bad unboxing, unboxing, fan mail, idub...",2017,11,14
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,...,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,114,"[racist superman, rudy, mancuso, king, bach, r...",2017,11,14
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,...,False,False,False,I know it's been a while since we did this sho...,CA,108,"[ryan, higa, higatv, nigahiga, i dare you, idy...",2017,11,14
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,...,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,66,"[edsheeran, ed sheeran, acoustic, live, cover,...",2017,11,14


### 13. For each (`month`, `country`) pair, the video with the largest number of views

In [19]:
months = final_dataframe.groupby(['month', 'country'])[['views', 'title']].max()
display(months)

                   views                                              title
month country
1     CA        43067983  🔴 LIVE: White House URGENT Press Briefing, Sar...
      DE        37728802               🚫 Meine Reaktion auf FASHION NO GO'S
      FR        37728802  🤼  Samantha dans tous ses états (2) 💛 Samantha...
      GB        90598955                   청하 (CHUNGHA) - Roller Coaster MV
      IN        42019590  🔴[Live] Tibba (Kapurthala) North India Federat...
...                  ...                                                ...
12    IN       125432237  🔴[Live] Sardulgarh (Mansa) Kabaddi Tournament ...
      KR       113876217                   😉 가수 박서진 송년콘서트에서 뽀식이 이용식 폭소만발 ^^
      MX       100912384  😱Wendy tiene un novio hombre?🍕🍕el cuñado de Ch...
      RU        52611730  🚙Поездка в Краснодарский край // станица Васюр...
      US       149376127          巨大なうさぎを癒すねこ。-Maru heals the huge rabbit.-

[77 rows x 2 columns]


### 14. Read all json files with the video categories

In [20]:
import json
import pandas as pd
JSON_list = ['CA_category_id.json', 'DE_category_id.json', 'FR_category_id.json', 'GB_category_id.json', 
             'IN_category_id.json', 'JP_category_id.json', 'KR_category_id.json', 
             'MX_category_id.json', 'RU_category_id.json', 'US_category_id.json']
dataframesj = []

for file in JSON_list:
    try:
        data = pd.read_json(file)
        dfj = pd.json_normalize(data['items'], sep='_') #transform from a hierarchical strcture to a flat one
        dataframesj.append(dfj)
            
    except pd.errors.EmptyDataError as ede:
        print(f"EmptyDataError: No data in {file}.")

final_dataframej = pd.concat(dataframesj, ignore_index=True)
final_dataframej = final_dataframej.drop(columns=['snippet_channelId','kind']) #the value of these columns is eqaul in the whole dataset so we drop them
final_dataframej.head(10)

,etag,id,snippet_title,snippet_assignable
0,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/Xy1mB4_yLrHy_BmKm...",1,Film & Animation,True
1,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/UZ1oLIIz2dxIhO45Z...",2,Autos & Vehicles,True
2,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",10,Music,True
3,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/HwXKamM1Q20q9BN-o...",15,Pets & Animals,True
4,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/9GQMSRjrZdHeb1OEM...",17,Sports,True
5,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/FJwVpGCVZ1yiJrqZb...",18,Short Movies,False
6,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/M-3iD9dwK7YJCafRf...",19,Travel & Events,True
7,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/WmA0qYEfjWsAoyJFS...",20,Gaming,True
8,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/EapFaGYG7K0StIXVf...",21,Videoblogging,False
9,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/xId8RX7vRN8rqkbYZ...",22,People & Blogs,True


### 15. For each country, determine how many videos have a category that is not assignable.

In [27]:
final_dataframe.loc[:,'category_id'] = final_dataframe['category_id'].astype(str) #transform into a string
#final_dataframej.loc[:,'id'] = final_dataframej['id'].astype(str)
final_dataframej.rename(columns={'id':'category_id','snippet_title':'category_name' }, inplace=True) #to merge the dataframes on the same column we rename it
final_dataframej_sub = final_dataframej[['category_id', 'category_name', 'snippet_assignable']]
final_dataframej_sub = final_dataframej_sub.drop_duplicates()

df_final = pd.merge(final_dataframe, final_dataframej_sub, on="category_id")

df_final

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,video_error_or_removed,description,country,cluster,supertag,year,month,day,category_name,snippet_assignable
0,n1WpP7iowLc,2017-11-14,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,102,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",2017,11,14,Music,True
1,0dBIkQ4Mz1M,2017-11-14,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,...,False,STill got a lot of packages. Probably will las...,CA,102,"[plush, bad unboxing, unboxing, fan mail, idub...",2017,11,14,Comedy,True
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,...,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,114,"[racist superman, rudy, mancuso, king, bach, r...",2017,11,14,Comedy,True
3,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,...,False,I know it's been a while since we did this sho...,CA,108,"[ryan, higa, higatv, nigahiga, i dare you, idy...",2017,11,14,Entertainment,True
4,2Vv-BfVoq4g,2017-11-14,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,...,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,66,"[edsheeran, ed sheeran, acoustic, live, cover,...",2017,11,14,Music,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373317,BZt0qjTWNhw,2018-06-14,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18 13:00:04+00:00,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,...,False,The Cat Who Caught the Laser - Aaron's Animals,US,78,"[aarons animals, aarons, animals, cat, cats, k...",2018,6,14,Pets & Animals,True
373318,1h7KV2sjUWY,2018-06-14,True Facts : Ant Mutualism,zefrank1,22,2018-05-18 01:00:06+00:00,[none],1064798,60008,382,...,False,NaN,US,6,[[none]],2018,6,14,People & Blogs,True
373319,D6Oy4LfoqsU,2018-06-14,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22+00:00,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,...,False,I had so much fun transforming Safiyas hair in...,US,105,[I gave safiya nygaard a perfect hair makeover...,2018,6,14,Entertainment,True
373320,oV0zkMe1K8s,2018-06-14,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,...,False,How Black Panther Should Have EndedWatch More ...,US,102,"[Black Panther, HISHE, Marvel, Infinity War, H...",2018,6,14,Film & Animation,True
373321,ooyjaVdt-jA,2018-06-14,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,...,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,102,"[call of duty, cod, activision, Black Ops 4]",2018,6,14,Gaming,True

In [34]:
#df_final.groupby('category_id').size()

In [31]:
df_finals = df_final[df_final['snippet_assignable'] == False]
df_finals

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,video_error_or_removed,description,country,cluster,supertag,year,month,day,category_name,snippet_assignable
263,AlrbKKGIcjI,2017-11-15,"Deivamagal Episode 1388, 14/11/17",VikatanTV,43,2017-11-14 15:00:00+00:00,"deivamagal|""deiva magal""|""deiva magal serial""|...",591632,3231,1327,...,False,Deivamagal Episode 1388\nSubscribe: https://go...,CA,90,"[deivamagal, deiva magal, deiva magal serial, ...",2017,11,15,Shows,False
348,mQbsY2KTFHk,2017-11-15,"Слуга Народа 2 - От любви до импичмента, 22 се...",Слуга народа,43,2017-11-14 18:45:58+00:00,"сериал|""сериал 2017""|""сериал 4к""|""сериал слуга...",437979,8787,287,...,False,Ze Kubiki - Спортивный влог Владимира Зеленско...,CA,112,"[сериал, сериал 2017, сериал 4к, сериал слуга ...",2017,11,15,Shows,False
555,QfmIUoZej9Q,2017-11-16,"Слуга Народа 2 - От любви до импичмента, 23 серия",Слуга народа,43,2017-11-15 18:42:55+00:00,"сериал|""сериал 2017""|""сериал 4к""|""сериал слуга...",467088,9228,220,...,False,Ze Kubiki - Спортивный влог Владимира Зеленско...,CA,112,"[сериал, сериал 2017, сериал 4к, сериал слуга ...",2017,11,16,Shows,False
680,5EBDXsTkg1E,2017-11-17,"Priyamanaval Episode 866, 16/11/17",VikatanTV,43,2017-11-16 17:00:00+00:00,"Priyamanaval 16.11.2017|""priyamanaval 866""|""Pr...",416189,2107,714,...,False,Priyamanaval Episode 866\nSubscribe: https://g...,CA,102,"[Priyamanaval 16.11.2017, priyamanaval 866, Pr...",2017,11,17,Shows,False
772,xOjlzuWakD4,2017-11-17,"Слуга Народа 2 - От любви до импичмента, 24 серия",Слуга народа,43,2017-11-16 18:48:38+00:00,"сериал|""сериал 2017""|""сериал 4к""|""сериал слуга...",487929,15866,378,...,False,Ze Kubiki - Спортивный влог Владимира Зеленско...,CA,112,"[сериал, сериал 2017, сериал 4к, сериал слуга ...",2017,11,17,Shows,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370905,V6ElE2xs48c,2018-06-02,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1324482,22413,608,...,False,"On an island full of Van Gundys, Stan gets tal...",US,126,"[bleacher report, br, nba, Stan Van Gundy, Jef...",2018,6,2,Shows,False
371108,V6ElE2xs48c,2018-06-03,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1332252,22461,610,...,False,"On an island full of Van Gundys, Stan gets tal...",US,126,"[bleacher report, br, nba, Stan Van Gundy, Jef...",2018,6,3,Shows,False
371312,V6ElE2xs48c,2018-06-04,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1340039,22504,615,...,False,"On an island full of Van Gundys, Stan gets tal...",US,126,"[bleacher report, br, nba, Stan Van Gundy, Jef...",2018,6,4,Shows,False
371514,V6ElE2xs48c,2018-06-05,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1345086,22542,615,...,False,"On an island full of Van Gundys, Stan gets tal...",US,126,"[bleacher report, br, nba, Stan Van Gundy, Jef...",2018,6,5,Shows,False
371717,V6ElE2xs48c,2018-06-06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1351321,22587,616,...,False,"On an island full of Van Gundys, Stan gets tal...",US,126,"[bleacher report, br, nba, Stan Van Gundy, Jef...",2018,6,6,Shows,False

In [33]:
df_finals.groupby('country').size()

country
CA    130
DE    110
FR    112
GB     20
IN    221
KR    167
MX      3
RU    195
US     57
dtype: int64